### ISSUE TITLE
2 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by EricTorresAndrade** [tessus/react-native-version-info#11] opened 2021-11-12 11:22 UTC
After follow step to install manual I am getting this error building 

react: 17.0.1
react-native: 0.64.0

<img width="753" alt="Captura de Pantalla 2021-11-12 a la(s) 5 19 02 a m" src="https://user-images.githubusercontent.com/87657657/141459029-0795d919-256b-4174-9e2e-0024556262fc.png">

**Comment by tessus** [comment] 2021-11-14 20:45
I am not able to reproduce this. We are using this module in Joplin (see [here](https://github.com/laurent22/joplin/blob/dev/packages/app-mobile/package.json)) and we don't get any errors.

I have been searching the Net for a bit and it seems this error happens, if you are using pods and react linking at the same time.

- https://stackoverflow.com/questions/48214603/duplicate-symbols-for-architecture-x86-64-ios-react-native
- https://stackoverflow.com/questions/63362421/ld-16-duplicate-symbols-for-architecture-x86-64-in-react-native-ios-developme
- https://reactnative.dev/docs/linking-libraries-ios

**Comment by tessus** [comment] 2022-07-14 03:22
Closing after no more feedback from OP.

**Closed by tessus** 2022-07-14 03:22 UTC
