### ISSUE TITLE
React-native-version-info not working

### ISSUE THREAD

**Issue by naveed1239** [tessus/react-native-version-info#12] opened 2022-08-24 11:24 UTC
React-native-version-info not working with **def enableSeparateBuildPerCPUArchitecture = true** in android.
When I create a **debug build** its working fine but with **release build** this library is not working

**Comment by tessus** [comment] 2022-08-24 12:04
Can you please add a bit more info?
What's the error message? Is there an Android debug log output?

**Comment by naveed1239** [comment] 2022-08-24 12:30
Thanks for the quick response. As of now I don't have any error message but
what my guess is, that library is sending wrong "VersionInfo.appVersion"
for android release build when  enableSeparateBuildPerCPUArchitecture =
true.

**Comment by tessus** [comment] 2022-08-25 21:40
What is the version number and what is shown? What about `bundleIdentifier` and `buildVersion`?
I really need more information. Is `0` shown or an empty string?

I looked into similar packages, but they all do the same thing.

**Comment by tessus** [comment] 2022-08-25 21:59
Additionally which packages are built when you set `enableSeparateBuildPerCPUArchitecture = true`?

What happens, if you remove the following lines:
https://github.com/tessus/react-native-version-info/blob/master/android/build.gradle#L16-L18

**Comment by tessus** [comment] 2022-09-06 11:58
I still can't reproduce your problem. Unless you provide more info, like a Android debug log, and answer my other questions I asked in the previous 2 comments, I'll close this issue.

I can re-open, when I get more info from you.

**Closed by tessus** 2022-09-06 11:58 UTC
